# Generated by Django 6.0.3 on 2026-07-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeidcounter_alter_employeeprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='shift_assigned',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Night')], default='Morning', max_length=10),
        ),
    ]
