# Generated by Django 6.0.3 on 2026-06-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitdetails', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdetails',
            name='shift_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
