# Generated by Django 6.0.4 on 2026-06-27 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitdetails', '0004_shiftdetails_shift_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftdetails',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shiftdetails',
            name='shift_date',
        ),
        migrations.RemoveField(
            model_name='shiftdetails',
            name='start_time',
        ),
        migrations.AddField(
            model_name='shiftdetails',
            name='shift_end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='shiftdetails',
            name='shift_end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='shiftdetails',
            name='shift_start_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 27, 12, 21, 18, 899899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='shiftdetails',
            name='shift_start_time',
            field=models.TimeField(default=None),
        ),
    ]
