# Generated by Django 6.0.3 on 2026-06-27 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitdetails', '0005_remove_shiftdetails_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetails',
            name='shift_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftdetails',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftdetails',
            name='shift_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shiftdetails',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
